-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) TOTAL_SALES
  FROM BOOK A
  JOIN BOOK_SALES B
    ON A.BOOK_ID = B.BOOK_ID
 WHERE (YEAR(B.SALES_DATE) = 2022 AND MONTH(B.SALES_DATE) = 1)
 GROUP BY 1
 ORDER BY 1