-- 코드를 입력하세요
SELECT
       EXTRACT(HOUR FROM DATETIME) HOUR
     , COUNT(ANIMAL_ID)  
  FROM ANIMAL_OUTS
 WHERE EXTRACT(HOUR FROM DATETIME) > 8 AND EXTRACT(HOUR FROM DATETIME) < 20 
 GROUP BY 1 
ORDER BY 1