-- 코드를 작성해주세요
SELECT
       COUNT(ID) FISH_COUNT
     , MAX(IFNULL(LENGTH, 10)) MAX_LENGTH
     , FISH_TYPE
  FROM FISH_INFO
 GROUP BY FISH_TYPE 
 HAVING SUM(LENGTH) / COUNT(LENGTH) >= 33
 ORDER BY FISH_TYPE