-- 코드를 입력하세요
SELECT
       A.MEMBER_ID
     , A.MEMBER_NAME
     , A.GENDER
     , TO_CHAR(A.DATE_OF_BIRTH, 'YYYY-MM-DD')
  FROM MEMBER_PROFILE A 
 WHERE SUBSTR(TO_CHAR(A.DATE_OF_BIRTH, 'YYYY-MM-DD'), 7, 1) = 3
   AND A.TLNO IS NOT NULL
   AND A.GENDER = 'W'
 ORDER BY A.MEMBER_ID ASC